### ISSUE TITLE
A problem of data loader with training process.

### ISSUE THREAD

**Issue by hgr215** [Pavelrst/DIP_Project#1]
Hi, I just download the code and download part of the **train-set of** open-images-dataset(for it is too big), and run _python kpn_train.py --dataset_dir ./open-images-dataset_, and some error happend:

`totalMemory: 11.91GiB freeMemory: 11.74GiB
2019-03-22 16:13:46.333703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-03-22 16:13:46.840112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-22 16:13:46.840181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-03-22 16:13:46.840197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-03-22 16:13:46.840743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wi                           th 11362 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:89:00.0, compute capability: 6.1)
Starting 4 writers
Initializers
Thread coordinator
Traceback (most recent call last):
  File "kpn_train.py", line 581, in <module>
    app.run()
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "kpn_train.py", line 575, in main
    train_merge_simple(filenames)
  File "kpn_train.py", line 539, in train_merge_simple
    _, loss, i = sess.run([train_step_g, total_loss, gs])
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (re                           quested 2, current size 0)
         [[Node: shuffle_batch = QueueDequeueManyV2[_class=["loc:@cond_27/Switch_1"], component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replic                           a:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
         [[Node: cond_20/Switch_1/_261 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost                           /replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_453_cond_20/Switch_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/ta                           sk:0/device:GPU:0"]()]]

Caused by op u'shuffle_batch', defined at:
  File "kpn_train.py", line 581, in <module>
    app.run()
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "kpn_train.py", line 575, in main
    train_merge_simple(filenames)
  File "kpn_train.py", line 171, in train_merge_simple
    degamma=2.2, to_shift=1., upscale=4, jitter=16, smalljitter=2)
  File "/home1/hgr5391/DIP_Project-master/Code/kpn_data_provider.py", line 160, in load_batch_hqjitter
    min_after_dequeue=min_queue)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
    name=name)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

**OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 2, cur                           rent size 0)**
         [[Node: shuffle_batch = QueueDequeueManyV2[_class=["loc:@cond_27/Switch_1"], component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replic                           a:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
         [[Node: cond_20/Switch_1/_261 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost                           /replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_453_cond_20/Switch_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/ta                           sk:0/device:GPU:0"]()]]`

why the read queue was closed during dataloading? Is there something I haven't done?
thanks a lot!

**Comment by hgr215** [comment]
> Hi, I just download the code and download part of the **train-set of** open-images-dataset(for it is too big), and run _python kpn_train.py --dataset_dir ./open-images-dataset_, and some error happend:
> 
> `totalMemory: 11.91GiB freeMemory: 11.74GiB
> 2019-03-22 16:13:46.333703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
> 2019-03-22 16:13:46.840112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-03-22 16:13:46.840181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0
> 2019-03-22 16:13:46.840197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0: N
> 2019-03-22 16:13:46.840743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wi th 11362 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:89:00.0, compute capability: 6.1)
> Starting 4 writers
> Initializers
> Thread coordinator
> Traceback (most recent call last):
> File "kpn_train.py", line 581, in 
> app.run()
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "kpn_train.py", line 575, in main
> train_merge_simple(filenames)
> File "kpn_train.py", line 539, in train_merge_simple
> _, loss, i = sess.run([train_step_g, total_loss, gs])
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
> run_metadata_ptr)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
> run_metadata)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (re quested 2, current size 0)
> [[Node: shuffle_batch = QueueDequeueManyV2[_class=["loc:@cond_27/Switch_1"], component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replic a:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
> [[Node: cond_20/Switch_1/_261 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost /replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_453_cond_20/Switch_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/ta sk:0/device:GPU:0"]]
> 
> Caused by op u'shuffle_batch', defined at:
> File "kpn_train.py", line 581, in 
> app.run()
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "kpn_train.py", line 575, in main
> train_merge_simple(filenames)
> File "kpn_train.py", line 171, in train_merge_simple
> degamma=2.2, to_shift=1., upscale=4, jitter=16, smalljitter=2)
> File "/home1/hgr5391/DIP_Project-master/Code/kpn_data_provider.py", line 160, in load_batch_hqjitter
> min_after_dequeue=min_queue)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
> name=name)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch
> dequeued = queue.dequeue_many(batch_size, name=name)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
> self._queue_ref, n=n, component_types=self._dtypes, name=name)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
> component_types=component_types, timeout_ms=timeout_ms, name=name)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
> return func(*args, **kwargs)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
> op_def=op_def)
> File "/home1/hgr5391/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> **OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 2, cur rent size 0)**
> [[Node: shuffle_batch = QueueDequeueManyV2[_class=["loc:@cond_27/Switch_1"], component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replic a:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
> [[Node: cond_20/Switch_1/_261 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost /replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_453_cond_20/Switch_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/ta sk:0/device:GPU:0"]]`
> 
> why the read queue was closed during dataloading? Is there something I haven't done?
> thanks a lot!

**Comment by hgr215** [comment]
solved
